[package]
name = "alumina-ui"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.27", default-features = false, features = ["glow"] }
egui = { version = "0.27" }
# The following are only pulled in when compiling for the web target
wasm-bindgen = { version = "0.2", optional = true }
wasm-bindgen-futures = { version = "0.4", optional = true }
console_error_panic_hook = { version = "0.1", optional = true }
wasm-logger = { version = "0.2", optional = true }
log = "0.4"
csgrs = { version = "0.18.0", default-features = false, features = ["delaunay", "f64", "stl-io", "dxf-io", "hashmap"] }
rfd = "^0.11.4"
uuid = { version = "1.17", features = ["js", "v4"] }
glow = "0.13.1"
bytemuck = "1.23.1"
egui_glow = "0.27.2"
nalgebra = "0.33.2"
geo = "0.29"

[features]
default = [
    "wasm-bindgen",
    "wasm-bindgen-futures",
    "console_error_panic_hook",
    "wasm-logger",
]

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
strip = "symbols"
debug-assertions = false
overflow-checks = false
panic = "abort"
incremental = false
