[build]
filehash = false

[tools.wasm-bindgen]               # ▼ run wasm-bindgen with the tiniest output
args = [
  "--target", "web",
  "--no-typescript",
  "--omit-default-module-path",
  "--remove-name-section",
  "--remove-producers-section",
]

[[hooks]]
stage   = "post_build"            # run after Trunk finished writing dist/
command = "bash"                  # use `cmd /C` or `pwsh` on Windows
command_arguments = [
  "-c",
  '''
set -euo pipefail

# 0) Run Binaryen optimiser (≈-10 – 30 %)
wasm-opt -Oz --vacuum --enable-bulk-memory-opt --enable-nontrapping-float-to-int -o "$TRUNK_STAGING_DIR/alumina-ui_bg.wasm" \
         "$TRUNK_STAGING_DIR/alumina-ui_bg.wasm"

# 1) Strip any leftover custom sections
wasm-tools strip "$TRUNK_STAGING_DIR/alumina-ui_bg.wasm" \
         -o "$TRUNK_STAGING_DIR/alumina-ui_bg.wasm"

# ──────────────────────────────────────────────────────────────────────
# 1) Strip Trunk’s auto-bootstrap & preload hints
#    (anything that still references the *uncompressed* artefacts).
#    ───────────────────────────────────────────────────────────────────
sed -i \
  -e '/rel="modulepreload".*alumina-ui\.js/d' \
  -e '/rel="preload".*alumina-ui_bg\.wasm/d' \
  -e '/import init.*,.*\/alumina-ui\.js/,/dispatchEvent.*TrunkApplicationStarted/d' \
  "$TRUNK_STAGING_DIR/index.html"

cp "$TRUNK_SOURCE_DIR/zstd.js" "$TRUNK_STAGING_DIR/zstd.js"
gzip -kf -9 "$TRUNK_STAGING_DIR/index.html"
gzip -kf -9 "$TRUNK_STAGING_DIR/alumina-ui.js"
gzip -kf -9 "$TRUNK_STAGING_DIR/zstd.js"

if command -v zstd >/dev/null; then
  zstd --ultra -22 -T0 -q -f \
       "$TRUNK_STAGING_DIR/alumina-ui_bg.wasm" \
       -o "$TRUNK_STAGING_DIR/alumina-ui_bg.wasm.zst"
fi
  '''
]
